-
  hosts: local
  connection: local
  sudo: yes
  tasks:
    - name: Update sshd_config to allow public key access
      copy: src=/provision/files/sshd_config dest=/etc/ssh/sshd_config
      notify:
        - restart ssh

    - name: Install required apt packages
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - zsh
        - wget

    - name: Download jq
      get_url: >
        url=http://stedolan.github.io/jq/download/linux64/jq
        dest=/sbin/jq
        mode=0555

    - name: Add netengine user
      user: name=netengine shell=/bin/zsh uid=1111

    - name: Pull down oh-my-zsh for netengine user
      git: >
        repo=git://github.com/robbyrussell/oh-my-zsh.git
        dest=/home/netengine/.oh-my-zsh
        accept_hostkey=yes
        update=no
      sudo_user: netengine

    - name: Add .zshrc for netengine user
      copy: >
        src=files/zshrc dest=/home/netengine/.zshrc
        owner=netengine
        group=netengine

    - name: Creates .ssh directory for netengine user
      file: path=/home/netengine/.ssh state=directory
      sudo_user: netengine

    - name: Update ssh_config to prevent hostkey problems while shelling between containers.
      copy: >
        src=/provision/files/ssh_config
        dest=/home/netengine/.ssh/config
        owner=netengine
        group=netengine

    - name: Give netengine user passwordless sudo
      lineinfile: "dest=/etc/sudoers insertafter=EOF line='netengine ALL=(ALL) NOPASSWD: ALL' regexp='netengine' state=present"

    - name: Download NE team public keys to netengine user
      get_url: >
        url=https://raw.githubusercontent.com/net-engine/dot-ssh/master/authorized_keys
        dest=/home/netengine/.ssh/authorized_keys
        mode=0600
        force=yes
      sudo_user: netengine

  handlers:
    - name: restart ssh
      service: name=ssh state=restarted

